frameworkVersion: '>=1.0.0 <2.0.0'

service: ${self:custom.productPhotos.failName}

custom:
  stage: ${opt:stage, self:provider.stage, self:custom.private.stage}
  private: ${file(../../private.yml)}
  helloRetail: ${file(../../helloRetail.yml)}
  productPhotos: ${file(../productPhotos.yml)}

provider:
  name: aws
  deploymentBucket: helloRetailBucket
  runtime: nodejs8.10
  profile: DEFAULT_PROFILE
  region: us-east-1

functions:
  fail:
    role:
      'Fn::GetAtt': [ FailRole, Arn ]
    handler: fail.handler
    environment:
      TABLE_PHOTO_ASSIGNMENTS_NAME:
        Fn::ImportValue: ${self:custom.productPhotos.exportPhotoAssignmentsTableName}

resources:
  Resources:
    # Log Group
    FailLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/${self:service}-dev-fail'
        RetentionInDays: 7
    # Role
    FailRole: # role for the assignment failing lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: devProductPhotosFail${self:custom.productPhotos.productPhotosVersion}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - DEFAULT_TEAM_POLICY
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ FailLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ FailLogGroup, Arn ]
                        - '*'
          - ${self:custom.productPhotos.deletePhotoAssignment}
  Outputs:
    FailLambdaName:
      Description: The Name of the Photo Assignments Fail Lambda
      Value:
        Ref: FailLambdaFunction
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsFailLambdaName}
    FailLambdaArn:
      Description: The Name of the Photo Assignments Fail Lambda
      Value:
        'Fn::GetAtt': [ FailLambdaFunction, Arn ]
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsFailLambdaArn}
