frameworkVersion: '>=1.0.0 <2.0.0'

service: product-photos-message

custom:
  stage: dev
  private: ${file(../../private.yml)}
  helloRetail: ${file(../../helloRetail.yml)}
  productPhotos: ${file(../productPhotos.yml)}

provider:
  name: aws
  deploymentBucket: helloRetailBucket
  runtime: nodejs8.10
  profile: DEFAULT_PROFILE
  region: us-east-1

functions:
  message:
    role:
      'Fn::GetAtt': [ MessageRole, Arn ]
    handler: message.handler
    environment:
      TWILIO_ACCOUNT_SID_ENCRYPTED: ${self:custom.private.twilio.accountSid}
      TWILIO_AUTH_TOKEN_ENCRYPTED: ${self:custom.private.twilio.authToken}
      TWILIO_NUMBER: ${self:custom.private.twilio.dev.number}

resources:
  Resources:
    # Log Group
    MessageLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/${self:service}-dev-message'
        RetentionInDays: 7
    # Role
    MessageRole: # role for the assignment messaging lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: devProductPhotosMessage1
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - DEFAULT_TEAM_POLICY
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ MessageLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ MessageLogGroup, Arn ]
                        - '*'
  Outputs:
    MessageLambdaName:
      Description: The Name of the Photo Assignments Message Lambda
      Value:
        Ref: MessageLambdaFunction
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsMessageLambdaName}
    MessageLambdaArn:
      Description: The ARN of the Photo Assignments Message Lambda
      Value:
        'Fn::GetAtt': [ MessageLambdaFunction, Arn ]
      Export:
        Name: ${self:custom.productPhotos.exportPhotoAssignmentsMessageLambdaArn}
