AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  NumberOfWorkers:
    Type: Number
    Description: 'How many concurrent workers do you want'
    Default: 4
  NumberOfChunks:
    Type: Number
    Description: 'How many index files do you want to consider'
    Default: 2
  IndexBucket:
    Type: String
    Description: 'Bucket to look for the index key'
    Default: 'commoncrawl'
  IndexKey:
    Type: String
    Description: 'Key for the index object'
    Default: 'crawl-data/CC-MAIN-2018-17/warc.paths.gz'
  SearchRegex:
    Type: String
    Description: 'The regular expression to apply to the data chunks'
    Default: '(\([0-9]{3}\) |[0-9]{3}-)[0-9]{3}-[0-9]{4}'

Resources:

  Drainer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.metric_handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 5
      Policies:
        - SQSPollerPolicy:
             QueueName:
                Fn::GetAtt: [ "MetricQueue", "QueueName" ]
        - CloudWatchPutMetricPolicy: {}
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:XXX:MetricQueue
            BatchSize: 10


  Worker:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 1024
      Timeout: 300
      Policies:
        - SQSPollerPolicy:
             QueueName:
                Fn::GetAtt: [ "CrawlQueue", "QueueName" ]
        - SQSPollerPolicy:
             QueueName:
                Fn::GetAtt: [ "MetricQueue", "QueueName" ]
        - SQSSendMessagePolicy:
             QueueName:
                Fn::GetAtt: [ "CrawlQueue", "QueueName" ]
        - SQSSendMessagePolicy:
             QueueName:
                Fn::GetAtt: [ "MetricQueue", "QueueName" ]
        - S3ReadPolicy:
             BucketName:  IndexBucket
        - CloudWatchPutMetricPolicy: {}
        # NB: this allows us to invoke all functions in the stack
        - LambdaInvokePolicy:
             FunctionName: AWS::StackName
      Environment:
        Variables:
          QUEUE_URL:  CrawlQueue
          METRIC_URL:  MetricQueue
          MAX_WORKERS:  NumberOfWorkers
          MAX_CHUNKS: NumberOfChunks
          CRAWL_INDEX_BUCKET:  IndexBucket
          CRAWL_INDEX_KEY:  IndexKey
  CrawlQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
  MetricQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30

Outputs:
  Worker:
    Value: Worker
  MetricQueue:
    Value: MetricQueue.QueueName
  CrawlQueue:
    Value: CrawlQueue.QueueName
